const config = {
  invalidEmailHosts: [
    "cldkid.com",
    "bongo.com",
    "tempmail.ninja",
    "dropmail.me",
    "126.com",
    "minimail.gq",
    "10mail.tk",
    "cloudkid.com",
    "onionmail.org",
    "smartnator.com",
    "vpsrec.com",
    "vasqa.com",
    "galotv.com",
    "ulforex.com",
    "rawr.com",
    "fallinhay.com",
    "bukhariansiddur.com",
    "pdflivres.com",
    "cricketworldcup2015news.com",
    "creative-journeys.com",
    "chatily.com",
    "coop1001facons.ca",
    "fuckgyz.eu.org",
    "gyzanonymous.ml",
    "dotfordevestiy.com",
    "starium.live",
    "szentivanyi.com",
    "ericszentivanyi.com",
    "minekits.eu",
  ],

  roleToAdd: "1082297670246334525",
  guildId: "921470609475633212",
  botId: "1082295690585190450",
  admins: ["connerow1115@gmail.com"],
};

export default config;
