name: Pull Request CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun i

      - name: Lint
        run: bun lint

      - name: Check code style
        run: bun format:check

      - name: Build
        run: bun run build
